/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/内存管理': RouteRecordInfo<
      '/posts/内存管理',
      '/posts/%E5%86%85%E5%AD%98%E7%AE%A1%E7%90%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/单例模式': RouteRecordInfo<
      '/posts/单例模式',
      '/posts/%E5%8D%95%E4%BE%8B%E6%A8%A1%E5%BC%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/可调用对象': RouteRecordInfo<
      '/posts/可调用对象',
      '/posts/%E5%8F%AF%E8%B0%83%E7%94%A8%E5%AF%B9%E8%B1%A1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/左值与右值': RouteRecordInfo<
      '/posts/左值与右值',
      '/posts/%E5%B7%A6%E5%80%BC%E4%B8%8E%E5%8F%B3%E5%80%BC',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/模板元编程': RouteRecordInfo<
      '/posts/模板元编程',
      '/posts/%E6%A8%A1%E6%9D%BF%E5%85%83%E7%BC%96%E7%A8%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/模板特化': RouteRecordInfo<
      '/posts/模板特化',
      '/posts/%E6%A8%A1%E6%9D%BF%E7%89%B9%E5%8C%96',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/stl-containers': RouteRecordInfo<
      '/posts/stl-containers',
      '/posts/stl-containers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser_4be4ac1557b3c25bc2195b4be1f86c3c/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/内存管理.md': {
      routes:
        | '/posts/内存管理'
      views:
        | never
    }
    'pages/posts/单例模式.md': {
      routes:
        | '/posts/单例模式'
      views:
        | never
    }
    'pages/posts/可调用对象.md': {
      routes:
        | '/posts/可调用对象'
      views:
        | never
    }
    'pages/posts/左值与右值.md': {
      routes:
        | '/posts/左值与右值'
      views:
        | never
    }
    'pages/posts/模板元编程.md': {
      routes:
        | '/posts/模板元编程'
      views:
        | never
    }
    'pages/posts/模板特化.md': {
      routes:
        | '/posts/模板特化'
      views:
        | never
    }
    'pages/posts/stl-containers.md': {
      routes:
        | '/posts/stl-containers'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
